vich_uploader:
    db_driver: orm

    mappings:
        articles_image:
            uri_prefix: /uploads/blog
            upload_destination: '%kernel.project_dir%/public/uploads/blog'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
